-- Migration: InitialCreate
-- Aplicando migration manualmente no PostgreSQL

START TRANSACTION;

CREATE TABLE IF NOT EXISTS credit_consult (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    numero_credito character varying(50) NOT NULL,
    numero_nfse character varying(50) NOT NULL,
    data_constituicao date NOT NULL,
    valor_issqn numeric(15,2) NOT NULL,
    tipo_credito character varying(50) NOT NULL,
    simples_nacional boolean NOT NULL,
    aliquota numeric(5,2) NOT NULL,
    valor_faturado numeric(15,2) NOT NULL,
    valor_deducao numeric(15,2) NOT NULL,
    base_calculo numeric(15,2) NOT NULL,
    CONSTRAINT "PK_credit_consult" PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS "IX_credit_consult_numero_credito" ON credit_consult (numero_credito);
CREATE INDEX IF NOT EXISTS "IX_credit_consult_numero_nfse" ON credit_consult (numero_nfse);
CREATE INDEX IF NOT EXISTS "IX_credit_consult_tipo_credito" ON credit_consult (tipo_credito);

-- Registrar migration no histórico
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251217012948_InitialCreate', '6.0.36')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;

